const quoteArray = [
    "YOU ARE BEAUTIFUL",
    "YOU ARE DOING YOUR BEST AT ANY GIVEN MOMENT",
    "YOU ARE WORTHY OF GREAT THINGS",
    "YOU ARE BRAVER THAN YOU THINK",
    "YOU ARE ENOUGH JUST AS YOU ARE",
    "YOU DESERVE TO BE LOVED AND TO BE HAPPY",
    "YOU DESERVE TO BE SUCCESSFUL",
    "YOU ARE SMART",
    "YOU CAN BECOME ANYTHING YOU DESIRE",
    "YOU ARE UNIQUE AND SPECIAL BECAUSE YOU ARE YOU",
    "YOU HAVE ALL THE POWER TO FACE ANY CHALLENGES THAT COME YOUR WAY",
    "YOU ARE STRONG"
  ]

  export default quoteArray